//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serviser.Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ServiserDbEntities : DbContext
    {
        public ServiserDbEntities()
            : base("name=ServiserDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<VehicleNames> VehicleNames { get; set; }
        public virtual DbSet<VehicleProblems> VehicleProblems { get; set; }
        public virtual DbSet<VehicleTypes> VehicleTypes { get; set; }
    
        public virtual ObjectResult<all_problems_Result> all_problems()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<all_problems_Result>("all_problems");
        }
    }
}
