//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serviser.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleNames
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VehicleNames()
        {
            this.VehicleProblems = new HashSet<VehicleProblems>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int VehicleId { get; set; }
    
        public virtual VehicleTypes VehicleTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleProblems> VehicleProblems { get; set; }
    }
}
