//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serviser_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public booking()
        {
            this.BiLLItem = new HashSet<BiLLItem>();
        }
    
        public int id { get; set; }
        public int mechanic_id { get; set; }
        public int customer_id { get; set; }
        public int booking_status_id { get; set; }
        public System.DateTime creation_date_time { get; set; }
        public Nullable<double> base_fare { get; set; }
        public Nullable<double> mechanic_latitude { get; set; }
        public Nullable<double> mechanic_longitude { get; set; }
        public Nullable<double> customer_longitude { get; set; }
        public Nullable<double> customer_latitude { get; set; }
        public Nullable<double> distance { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BiLLItem> BiLLItem { get; set; }
        public virtual bookingStatus bookingStatus { get; set; }
        public virtual customerProfile customerProfile { get; set; }
        public virtual mechanicProfile mechanicProfile { get; set; }
    }
}
