//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serviser_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class offerMechanicBridge
    {
        public int mechanic_id { get; set; }
        public int offer_id { get; set; }
        public int id { get; set; }
    
        public virtual mechanicProfile mechanicProfile { get; set; }
    }
}
