//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serviser_Web
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ServiserDBEntities : DbContext
    {
        public ServiserDBEntities()
            : base("name=ServiserDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<booking> booking { get; set; }
        public virtual DbSet<bookingStatus> bookingStatus { get; set; }
        public virtual DbSet<customerOffer> customerOffer { get; set; }
        public virtual DbSet<customerProfile> customerProfile { get; set; }
        public virtual DbSet<mechanicOffers> mechanicOffers { get; set; }
        public virtual DbSet<mechanicProfile> mechanicProfile { get; set; }
        public virtual DbSet<Mechanic_sNotification> Mechanic_sNotification { get; set; }
        public virtual DbSet<offerMechanicBridge> offerMechanicBridge { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<vehicleName> vehicleName { get; set; }
        public virtual DbSet<vehicleProblems> vehicleProblems { get; set; }
        public virtual DbSet<VehicleType> VehicleType { get; set; }
        public virtual DbSet<BiLLItem> BiLLItem { get; set; }
    }
}
