//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serviser_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehicleProblems
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vehicleProblems()
        {
            this.BiLLItem = new HashSet<BiLLItem>();
            this.mechanicProfile = new HashSet<mechanicProfile>();
        }
    
        public int id { get; set; }
        public int Vehicle_name_id { get; set; }
        public string Name { get; set; }
        public int min_rate { get; set; }
        public int max_rate { get; set; }
    
        public virtual vehicleName vehicleName { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BiLLItem> BiLLItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mechanicProfile> mechanicProfile { get; set; }
    }
}
